# Generated by Django 4.1.4 on 2022-12-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_category_categorymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostmodel',
            old_name='post_title',
            new_name='author',
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
