# Generated by Django 4.1.4 on 2022-12-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpostmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='slug',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
    ]
